version: '3'

services:
    redismod:
        image: redislabs/redismod
        restart: always
        volumes:
            # Location of dump.rdb, containing the journeys graph.
            - redis_data:/data/
        ports:
            - 6379:6379

    backend:
        depends_on:
            - redismod
        image: nycbike:latest
        command: [ "--redis=redismod:6379", "--port=3000"]
        restart: always

    nginx: 
        depends_on:
            - backend
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/build:/etc/nginx/html/
        ports:
            - 80:80
            - 443:443

volumes:
    redis_data: